#!/bin/bash

docker run -it --rm -w "${PWD}" -v "${PWD}:${PWD}"\
                      -v //var/run/docker.sock:/var/run/docker.sock\
                      -v wrapper-sbin:/usr/local/sbin/\
                      -v wrapper-bundle:/root/.docker-bundle/\
                      dockerbundle/wrapper:latest $*
