version: '3'
services:
  redis:
    command: redis-server --appendonly yes
    image: redis:3.2.11-alpine
    restart: always
    networks:
      lan:
    volumes:
      - redis:/data
  db:
    image: postgres:10.4-alpine
    restart: always
    networks:
      lan:
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build: .
    image: ${PROJECT_NAME}
    restart: always
    environment:
      DOCKER_ENV: $ENV
      DATABASE_HOSTNAME: db
      REDIS_URL: 'redis://redis:6379/'
      LINES: 40
      COLUMNS: 120
    working_dir: /home/${PROJECT_NAME}
    tmpfs: /tmp
    expose:
      - 3000
    networks:
      lan:
    volumes:
      # project folder
      - ../:/home/${PROJECT_NAME}
      # depends save folder
      - bundle:/usr/local/bundle
      - yarn:/usr/local/share/.cache/yarn
      - node_modules:/home/${PROJECT_NAME}/node_modules
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
volumes:
  redis:
  db:
  node_modules:
  yarn:
    external:
      name: ${PROJECT_NAME}_yarn
  bundle:
    external:
      name: ${PROJECT_NAME}_bundle
networks:
  lan:
