version: '3'
services:
  redis:
    image: redis:3.2.11-alpine
  db:
    image: postgres:10.4-alpine
    volumes:
      - db:/var/lib/postgresql/data
  app:
    image: dockerbundle/rails
    environment:
      DATABASE_HOSTNAME: db
      LINES: 40
      COLUMNS: 120
    working_dir: /home/${PROJECT_NAME}
    tmpfs: /tmp
    expose:
      - 3000
    volumes:
      # project folder
      - ../:/home/${PROJECT_NAME}
      # depends save folder
      - bundle:/usr/local/bundle
      - yarn:/usr/local/share/.cache/yarn
      - node_modules:/home/${PROJECT_NAME}/node_modules
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
volumes:
  db:
  node_modules:
    external:
      name: ${PROJECT_NAME}_node_modules
  yarn:
    external:
      name: ${PROJECT_NAME}_yarn
  bundle:
    external:
      name: ${PROJECT_NAME}_bundle
