#!/bin/bash

set -e

CURRENT_DIR="$PWD/$(dirname "$0")"
DIR=$(dirname "$CURRENT_DIR")
IMAGE=docker-bundle
echo Enter Docker env...may wait...................
docker build "$CURRENT_DIR" -f "$CURRENT_DIR"/Dockerfile.w -t $IMAGE
docker run --rm -it -v //var/run/docker.sock:/var/run/docker.sock -v "$DIR:$DIR" -w "$DIR" $IMAGE $*

